{
 "title": "Loki Log Volume",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Main",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Volume by file ($interval interval)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(count_over_time({host!=\"docker-desktop\",filename=~\"/.*\"}[$interval])) by (filename)",
     "legendFormat": "{{filename}}"
    }
   ]
  },
  {
   "title": "5 Most Recent Synthetic Log Entries",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "{host!=\"docker-desktop\",filename=\"/logs/synthetic/synthetic.log\"}",
     "maxLines": 5
    }
   ]
  },
  {
   "title": "100 Most Recent Log Entries",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{host!=\"docker-desktop\",filename=~\"/.*\"}",
     "maxLines": 100
    }
   ]
  }
 ]
}
{
 "title": "Ping Results",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "10s,30s,1m,5m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "host",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Ping Times ($interval interval)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(avg_over_time(\n{host=~\".+\", host=\"docker\", filename=~\"/logs/ping/.*\", target=~\"$host\" } \n|= \"time=\"\n| regexp \"target=(?P<target>[^ ]+)\"\n| regexp \"time=(?P<time>[^ ]+)\"\n| unwrap time\n[$interval]\n)) by (target)\n\n",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Packet Loss - External Hosts ($interval interval)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "avg(avg_over_time(\n{ filename=~\"/logs/ping/.*\", target!=\"\", target!~\"internal-.*\" } \n|= \"transmitted\"\n| logfmt \n| line_format \"pct={{divf .received .transmitted | mulf 100 | sub 100 }}\"\n| logfmt \n| unwrap pct\n| __error__!=\"SampleExtractionErr\"\n[$interval]\n)) \n\n",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Packet Loss by Host - External Hosts ($interval interval)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 23, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "avg(avg_over_time(\n{ filename=~\"/logs/ping/.*\", target != \"\", target!~\"internal-.*\", target=~\"$host\" } \n|= \"transmitted\"\n| logfmt \n| line_format \"pct={{divf .received .transmitted | mulf 100 | sub 100 }}\"\n| logfmt \n| unwrap pct\n| __error__!=\"SampleExtractionErr\"\n[$interval]\n)) by (target)\n\n",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Packet Loss by Host - Internal Host ($interval interval)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 23, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "avg(avg_over_time(\n{ filename=~\"/logs/ping/.*\", target != \"\", target=~\"internal-.*\", target=~\"$host\"} \n|= \"transmitted\"\n| logfmt \n| line_format \"pct={{divf .received .transmitted | mulf 100 | sub 100 }}\"\n| logfmt \n| unwrap pct\n| __error__!=\"SampleExtractionErr\"\n[$interval]\n)) by (target)\n\n",
     "legendFormat": "{{target}}"
    }
   ]
  }
 ]
}
{
 "title": "Ping Results - Internal vs External",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "10s,30s,1m,5m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "host",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Ping Times ($interval interval)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(avg_over_time(\n{host=~\".+\", host=\"docker\", filename=~\"/logs/ping/.*\", target!=\"\", target=~\"$host\" } \n|= \"time=\"\n| regexp \"target=(?P<target>[^ ]+)\"\n| regexp \"time=(?P<time>[^ ]+)\"\n| unwrap time\n[$interval]\n)) by (target)\n\n",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Packet Loss - External Hosts ($interval interval)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "avg(avg_over_time(\n{ filename=~\"/logs/ping/.*\", target!=\"\", target!~\"internal-.*\", target=~\"$host\" } \n|= \"transmitted\"\n| logfmt \n| line_format \"pct={{divf .received .transmitted | mulf 100 | sub 100 }}\"\n| logfmt \n| unwrap pct\n| __error__!=\"SampleExtractionErr\"\n[$interval]\n)) \n\n",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Packet Loss - Interal Hosts ($interval interval)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 11, "y": 14 },
   "targets": [
    {
     "expr": "avg(avg_over_time(\n{ filename=~\"/logs/ping/.*\", target!=\"\", target=~\"internal-.*\", target=~\"$host\" } \n|= \"transmitted\"\n| logfmt \n| line_format \"pct={{divf .received .transmitted | mulf 100 | sub 100 }}\"\n| logfmt \n| unwrap pct\n| __error__!=\"SampleExtractionErr\"\n[$interval]\n)) \n\n",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Packet Loss by Host - External Hosts ($interval interval)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "avg(avg_over_time(\n{ filename=~\"/logs/ping/.*\", target != \"\", target!~\"internal-.*\", target=~\"$host\" } \n|= \"transmitted\"\n| logfmt \n| line_format \"pct={{divf .received .transmitted | mulf 100 | sub 100 }}\"\n| logfmt \n| unwrap pct\n| __error__!=\"SampleExtractionErr\"\n[$interval]\n)) by (target)\n\n",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Packet Loss by Host - Internal Host ($interval interval)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 11, "y": 25 },
   "targets": [
    {
     "expr": "avg(avg_over_time(\n{ filename=~\"/logs/ping/.*\", target != \"\", target=~\"internal-.*\", target=~\"$host\" } \n|= \"transmitted\"\n| logfmt \n| line_format \"pct={{divf .received .transmitted | mulf 100 | sub 100 }}\"\n| logfmt \n| unwrap pct\n| __error__!=\"SampleExtractionErr\"\n[$interval]\n)) by (target)\n\n",
     "legendFormat": "{{target}}"
    }
   ]
  }
 ]
}